import {
  AccessibilityIcon,
  ActivityLogIcon,
  AlignBaselineIcon,
  AlignBottomIcon,
  AlignCenterHorizontallyIcon,
  AlignCenterVerticallyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AllSidesIcon,
  AngleIcon,
  ArchiveIcon,
  ArrowBottomLeftIcon,
  ArrowBottomRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTopLeftIcon,
  ArrowTopRightIcon,
  ArrowUpIcon,
  AspectRatioIcon,
  AvatarIcon,
  BackpackIcon,
  BarChartIcon,
  BellIcon,
  BlendingModeIcon,
  BookmarkIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderDashedIcon,
  BorderDottedIcon,
  BorderLeftIcon,
  BorderNoneIcon,
  BorderRightIcon,
  BorderSolidIcon,
  BorderSplitIcon,
  BorderStyleIcon,
  BorderTopIcon,
  BoxIcon,
  BoxModelIcon,
  ButtonIcon,
  CalendarIcon,
  CameraIcon,
  CardStackIcon,
  CardStackMinusIcon,
  CardStackPlusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretSortIcon,
  CaretUpIcon,
  ChatBubbleIcon,
  CheckCircledIcon,
  CheckIcon,
  CheckboxIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleBackslashIcon,
  CircleIcon,
  ClipboardIcon,
  ClockIcon,
  CodeIcon,
  CodeSandboxLogoIcon,
  ColumnSpacingIcon,
  ColumnsIcon,
  CommitIcon,
  Component1Icon,
  Component2Icon,
  ComponentBooleanIcon,
  ComponentInstanceIcon,
  ComponentNoneIcon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CopyIcon,
  CornerBottomLeftIcon,
  CornerBottomRightIcon,
  CornerTopLeftIcon,
  CornerTopRightIcon,
  CornersIcon,
  CountdownTimerIcon,
  CounterClockwiseClockIcon,
  CropIcon,
  Cross1Icon,
  Cross2Icon,
  CrossCircledIcon,
  Crosshair1Icon,
  Crosshair2Icon,
  CubeIcon,
  CursorArrowIcon,
  CursorTextIcon,
  DashIcon,
  DesktopIcon,
  DimensionsIcon,
  DiscIcon,
  DividerHorizontalIcon,
  DividerVerticalIcon,
  DotIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DoubleArrowDownIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DoubleArrowUpIcon,
  DownloadIcon,
  DragHandleDots1Icon,
  DragHandleDots2Icon,
  DragHandleHorizontalIcon,
  DragHandleVerticalIcon,
  DrawingPinIcon,
  DrawingPinFilledIcon,
  DropdownMenuIcon,
  EnterIcon,
  EnterFullScreenIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  ExitFullScreenIcon,
  ExternalLinkIcon,
  EyeClosedIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  FaceIcon,
  FigmaLogoIcon,
  FileIcon,
  FileMinusIcon,
  FilePlusIcon,
  FileTextIcon,
  FontBoldIcon,
  FontFamilyIcon,
  FontItalicIcon,
  FontRomanIcon,
  FontSizeIcon,
  FontStyleIcon,
  FrameIcon,
  FramerLogoIcon,
  GearIcon,
  GitHubLogoIcon,
  GlobeIcon,
  GridIcon,
  GroupIcon,
  Half1Icon,
  Half2Icon,
  HamburgerMenuIcon,
  HandIcon,
  HeadingIcon,
  HeartIcon,
  HeartFilledIcon,
  HomeIcon,
  IconJarLogoIcon,
  IdCardIcon,
  ImageIcon,
  InfoCircledIcon,
  InputIcon,
  InstagramLogoIcon,
  KeyboardIcon,
  LapTimerIcon,
  LaptopIcon,
  LayoutIcon,
  LetterCaseCapitalizeIcon,
  LetterCaseLowercaseIcon,
  LetterCaseToggleIcon,
  LetterCaseUppercaseIcon,
  LetterSpacingIcon,
  LightningBoltIcon,
  LineHeightIcon,
  Link1Icon,
  Link2Icon,
  LinkBreak1Icon,
  LinkBreak2Icon,
  LinkNone1Icon,
  LinkNone2Icon,
  LinkedInLogoIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  LoopIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MarginIcon,
  MaskOffIcon,
  MaskOnIcon,
  MinusIcon,
  MixIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  MoonIcon,
  MoveIcon,
  NotionLogoIcon,
  OpacityIcon,
  OpenInNewWindowIcon,
  OverlineIcon,
  PaddingIcon,
  PaperPlaneIcon,
  PauseIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PieChartIcon,
  PilcrowIcon,
  PinBottomIcon,
  PinLeftIcon,
  PinRightIcon,
  PinTopIcon,
  PlayIcon,
  PlusIcon,
  QuestionMarkCircledIcon,
  QuestionMarkIcon,
  QuoteIcon,
  RadiobuttonIcon,
  ReaderIcon,
  ReloadIcon,
  ResetIcon,
  ResumeIcon,
  RocketIcon,
  RotateCounterClockwiseIcon,
  RowSpacingIcon,
  RowsIcon,
  RulerHorizontalIcon,
  RulerSquareIcon,
  ScissorsIcon,
  SectionIcon,
  SewingPinIcon,
  SewingPinFilledIcon,
  ShadowIcon,
  ShadowInnerIcon,
  ShadowNoneIcon,
  ShadowOuterIcon,
  Share1Icon,
  Share2Icon,
  ShuffleIcon,
  SizeIcon,
  SketchLogoIcon,
  SlashIcon,
  SliderIcon,
  SpaceBetweenHorizontallyIcon,
  SpaceBetweenVerticallyIcon,
  SpaceEvenlyHorizontallyIcon,
  SpaceEvenlyVerticallyIcon,
  SpeakerLoudIcon,
  SpeakerModerateIcon,
  SpeakerOffIcon,
  SpeakerQuietIcon,
  SquareIcon,
  StackIcon,
  StarIcon,
  StarFilledIcon,
  StitchesLogoIcon,
  StopIcon,
  StopwatchIcon,
  StretchHorizontallyIcon,
  StretchVerticallyIcon,
  StrikethroughIcon,
  SunIcon,
  SwitchIcon,
  SymbolIcon,
  TableIcon,
  TargetIcon,
  TextIcon,
  TextAlignBottomIcon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignMiddleIcon,
  TextAlignRightIcon,
  TextAlignTopIcon,
  TextNoneIcon,
  ThickArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  TimerIcon,
  TokensIcon,
  TrackNextIcon,
  TrackPreviousIcon,
  TransparencyGridIcon,
  TrashIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  TwitterLogoIcon,
  UnderlineIcon,
  UpdateIcon,
  UploadIcon,
  ValueIcon,
  ValueNoneIcon,
  VercelLogoIcon,
  VideoIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewNoneIcon,
  ViewVerticalIcon,
  WidthIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@radix-ui/react-icons";

export const IconsList: Record<string, Record<string, JSX.Element>> = 
{
  "A": {
    "AccessibilityIcon": <AccessibilityIcon />,
    "ActivityLogIcon": <ActivityLogIcon />,
    "AlignBaselineIcon": <AlignBaselineIcon />,
    "AlignBottomIcon": <AlignBottomIcon />,
    "AlignCenterHorizontallyIcon": <AlignCenterHorizontallyIcon />,
    "AlignCenterVerticallyIcon": <AlignCenterVerticallyIcon />,
    "AlignLeftIcon": <AlignLeftIcon />,
    "AlignRightIcon": <AlignRightIcon />,
    "AlignTopIcon": <AlignTopIcon />,
    "AllSidesIcon": <AllSidesIcon />,
    "AngleIcon": <AngleIcon />,
    "ArchiveIcon": <ArchiveIcon />,
    "ArrowBottomLeftIcon": <ArrowBottomLeftIcon />,
    "ArrowBottomRightIcon": <ArrowBottomRightIcon />,
    "ArrowDownIcon": <ArrowDownIcon />,
    "ArrowLeftIcon": <ArrowLeftIcon />,
    "ArrowRightIcon": <ArrowRightIcon />,
    "ArrowTopLeftIcon": <ArrowTopLeftIcon />,
    "ArrowTopRightIcon": <ArrowTopRightIcon />,
    "ArrowUpIcon": <ArrowUpIcon />,
    "AspectRatioIcon": <AspectRatioIcon />,
    "AvatarIcon": <AvatarIcon />,
  },
  "B": {
    "BackpackIcon": <BackpackIcon />,
    "BarChartIcon": <BarChartIcon />,
    "BellIcon": <BellIcon />,
    "BlendingModeIcon": <BlendingModeIcon />,
    "BookmarkIcon": <BookmarkIcon />,
    "BorderAllIcon": <BorderAllIcon />,
    "BorderBottomIcon": <BorderBottomIcon />,
    "BorderDashedIcon": <BorderDashedIcon />,
    "BorderDottedIcon": <BorderDottedIcon />,
    "BorderLeftIcon": <BorderLeftIcon />,
    "BorderNoneIcon": <BorderNoneIcon />,
    "BorderRightIcon": <BorderRightIcon />,
    "BorderSolidIcon": <BorderSolidIcon />,
    "BorderSplitIcon": <BorderSplitIcon />,
    "BorderStyleIcon": <BorderStyleIcon />,
    "BorderTopIcon": <BorderTopIcon />,
    "BoxIcon": <BoxIcon />,
    "BoxModelIcon": <BoxModelIcon />,
    "ButtonIcon": <ButtonIcon />,
  },
  "C": {
    "CalendarIcon": <CalendarIcon />,
    "CameraIcon": <CameraIcon />,
    "CardStackIcon": <CardStackIcon />,
    "CardStackMinusIcon": <CardStackMinusIcon />,
    "CardStackPlusIcon": <CardStackPlusIcon />,
    "CaretDownIcon": <CaretDownIcon />,
    "CaretLeftIcon": <CaretLeftIcon />,
    "CaretRightIcon": <CaretRightIcon />,
    "CaretSortIcon": <CaretSortIcon />,
    "CaretUpIcon": <CaretUpIcon />,
    "ChatBubbleIcon": <ChatBubbleIcon />,
    "CheckCircledIcon": <CheckCircledIcon />,
    "CheckIcon": <CheckIcon />,
    "CheckboxIcon": <CheckboxIcon />,
    "ChevronDownIcon": <ChevronDownIcon />,
    "ChevronLeftIcon": <ChevronLeftIcon />,
    "ChevronRightIcon": <ChevronRightIcon />,
    "ChevronUpIcon": <ChevronUpIcon />,
    "CircleBackslashIcon": <CircleBackslashIcon />,
    "CircleIcon": <CircleIcon />,
    "ClipboardIcon": <ClipboardIcon />,
    "ClockIcon": <ClockIcon />,
    "CodeIcon": <CodeIcon />,
    "CodeSandboxLogoIcon": <CodeSandboxLogoIcon />,
    "ColumnSpacingIcon": <ColumnSpacingIcon />,
    "ColumnsIcon": <ColumnsIcon />,
    "CommitIcon": <CommitIcon />,
    "Component1Icon": <Component1Icon />,
    "Component2Icon": <Component2Icon />,
    "ComponentBooleanIcon": <ComponentBooleanIcon />,
    "ComponentInstanceIcon": <ComponentInstanceIcon />,
    "ComponentNoneIcon": <ComponentNoneIcon />,
    "ComponentPlaceholderIcon": <ComponentPlaceholderIcon />,
    "ContainerIcon": <ContainerIcon />,
    "CookieIcon": <CookieIcon />,
    "CopyIcon": <CopyIcon />,
    "CornerBottomLeftIcon": <CornerBottomLeftIcon />,
    "CornerBottomRightIcon": <CornerBottomRightIcon />,
    "CornerTopLeftIcon": <CornerTopLeftIcon />,
    "CornerTopRightIcon": <CornerTopRightIcon />,
    "CornersIcon": <CornersIcon />,
    "CountdownTimerIcon": <CountdownTimerIcon />,
    "CounterClockwiseClockIcon": <CounterClockwiseClockIcon />,
    "CropIcon": <CropIcon />,
    "Cross1Icon": <Cross1Icon />,
    "Cross2Icon": <Cross2Icon />,
    "CrossCircledIcon": <CrossCircledIcon />,
    "Crosshair1Icon": <Crosshair1Icon />,
    "Crosshair2Icon": <Crosshair2Icon />,
    "CubeIcon": <CubeIcon />,
    "CursorArrowIcon": <CursorArrowIcon />,
    "CursorTextIcon": <CursorTextIcon />,
  },
  "D": {
    "DashIcon": <DashIcon />,
    "DesktopIcon": <DesktopIcon />,
    "DimensionsIcon": <DimensionsIcon />,
    "DiscIcon": <DiscIcon />,
    "DividerHorizontalIcon": <DividerHorizontalIcon />,
    "DividerVerticalIcon": <DividerVerticalIcon />,
    "DotIcon": <DotIcon />,
    "DotFilledIcon": <DotFilledIcon />,
    "DotsHorizontalIcon": <DotsHorizontalIcon />,
    "DotsVerticalIcon": <DotsVerticalIcon />,
    "DoubleArrowDownIcon": <DoubleArrowDownIcon />,
    "DoubleArrowLeftIcon": <DoubleArrowLeftIcon />,
    "DoubleArrowRightIcon": <DoubleArrowRightIcon />,
    "DoubleArrowUpIcon": <DoubleArrowUpIcon />,
    "DownloadIcon": <DownloadIcon />,
    "DragHandleDots1Icon": <DragHandleDots1Icon />,
    "DragHandleDots2Icon": <DragHandleDots2Icon />,
    "DragHandleHorizontalIcon": <DragHandleHorizontalIcon />,
    "DragHandleVerticalIcon": <DragHandleVerticalIcon />,
    "DrawingPinIcon": <DrawingPinIcon />,
    "DrawingPinFilledIcon": <DrawingPinFilledIcon />,
    "DropdownMenuIcon": <DropdownMenuIcon />,
  },
  "E": {
    "EnterIcon": <EnterIcon />,
    "EnterFullScreenIcon": <EnterFullScreenIcon />,
    "EnvelopeClosedIcon": <EnvelopeClosedIcon />,
    "EnvelopeOpenIcon": <EnvelopeOpenIcon />,
    "ExclamationTriangleIcon": <ExclamationTriangleIcon />,
    "ExitIcon": <ExitIcon />,
    "ExitFullScreenIcon": <ExitFullScreenIcon />,
    "ExternalLinkIcon": <ExternalLinkIcon />,
    "EyeClosedIcon": <EyeClosedIcon />,
    "EyeNoneIcon": <EyeNoneIcon />,
    "EyeOpenIcon": <EyeOpenIcon />,
  },
  "F": {
    "FaceIcon": <FaceIcon />,
    "FigmaLogoIcon": <FigmaLogoIcon />,
    "FileIcon": <FileIcon />,
    "FileMinusIcon": <FileMinusIcon />,
    "FilePlusIcon": <FilePlusIcon />,
    "FileTextIcon": <FileTextIcon />,
    "FontBoldIcon": <FontBoldIcon />,
    "FontFamilyIcon": <FontFamilyIcon />,
    "FontItalicIcon": <FontItalicIcon />,
    "FontRomanIcon": <FontRomanIcon />,
    "FontSizeIcon": <FontSizeIcon />,
    "FontStyleIcon": <FontStyleIcon />,
    "FrameIcon": <FrameIcon />,
    "FramerLogoIcon": <FramerLogoIcon />,
  },
  "G": {
    "GearIcon": <GearIcon />,
    "GitHubLogoIcon": <GitHubLogoIcon />,
    "GlobeIcon": <GlobeIcon />,
    "GridIcon": <GridIcon />,
    "GroupIcon": <GroupIcon />,
  },
  "H": {
    "Half1Icon": <Half1Icon />,
    "Half2Icon": <Half2Icon />,
    "HamburgerMenuIcon": <HamburgerMenuIcon />,
    "HandIcon": <HandIcon />,
    "HeadingIcon": <HeadingIcon />,
    "HeartIcon": <HeartIcon />,
    "HeartFilledIcon": <HeartFilledIcon />,
    "HomeIcon": <HomeIcon />,
  },
  "I": {
    "IconJarLogoIcon": <IconJarLogoIcon />,
    "IdCardIcon": <IdCardIcon />,
    "ImageIcon": <ImageIcon />,
    "InfoCircledIcon": <InfoCircledIcon />,
    "InputIcon": <InputIcon />,
    "InstagramLogoIcon": <InstagramLogoIcon />,
  },
  "K": {
    "KeyboardIcon": <KeyboardIcon />,
  },
  "L": {
    "LapTimerIcon": <LapTimerIcon />,
    "LaptopIcon": <LaptopIcon />,
    "LayoutIcon": <LayoutIcon />,
    "LetterCaseCapitalizeIcon": <LetterCaseCapitalizeIcon />,
    "LetterCaseLowercaseIcon": <LetterCaseLowercaseIcon />,
    "LetterCaseToggleIcon": <LetterCaseToggleIcon />,
    "LetterCaseUppercaseIcon": <LetterCaseUppercaseIcon />,
    "LetterSpacingIcon": <LetterSpacingIcon />,
    "LightningBoltIcon": <LightningBoltIcon />,
    "LineHeightIcon": <LineHeightIcon />,
    "Link1Icon": <Link1Icon />,
    "Link2Icon": <Link2Icon />,
    "LinkBreak1Icon": <LinkBreak1Icon />,
    "LinkBreak2Icon": <LinkBreak2Icon />,
    "LinkNone1Icon": <LinkNone1Icon />,
    "LinkNone2Icon": <LinkNone2Icon />,
    "LinkedInLogoIcon": <LinkedInLogoIcon />,
    "ListBulletIcon": <ListBulletIcon />,
    "LockClosedIcon": <LockClosedIcon />,
    "LockOpen1Icon": <LockOpen1Icon />,
    "LockOpen2Icon": <LockOpen2Icon />,
    "LoopIcon": <LoopIcon />,
  },
  "M": {
    "MagicWandIcon": <MagicWandIcon />,
    "MagnifyingGlassIcon": <MagnifyingGlassIcon />,
    "MarginIcon": <MarginIcon />,
    "MaskOffIcon": <MaskOffIcon />,
    "MaskOnIcon": <MaskOnIcon />,
    "MinusIcon": <MinusIcon />,
    "MixIcon": <MixIcon />,
    "MixerHorizontalIcon": <MixerHorizontalIcon />,
    "MixerVerticalIcon": <MixerVerticalIcon />,
    "MoonIcon": <MoonIcon />,
    "MoveIcon": <MoveIcon />,
  },
  "N": {
    "NotionLogoIcon": <NotionLogoIcon />,
  },
  "O": {
    "OpacityIcon": <OpacityIcon />,
    "OpenInNewWindowIcon": <OpenInNewWindowIcon />,
    "OverlineIcon": <OverlineIcon />,
  },
  "P": {
    "PaddingIcon": <PaddingIcon />,
    "PaperPlaneIcon": <PaperPlaneIcon />,
    "PauseIcon": <PauseIcon />,
    "Pencil1Icon": <Pencil1Icon />,
    "Pencil2Icon": <Pencil2Icon />,
    "PersonIcon": <PersonIcon />,
    "PieChartIcon": <PieChartIcon />,
    "PilcrowIcon": <PilcrowIcon />,
    "PinBottomIcon": <PinBottomIcon />,
    "PinLeftIcon": <PinLeftIcon />,
    "PinRightIcon": <PinRightIcon />,
    "PinTopIcon": <PinTopIcon />,
    "PlayIcon": <PlayIcon />,
    "PlusIcon": <PlusIcon />,
  },
  "Q": {
    "QuestionMarkCircledIcon": <QuestionMarkCircledIcon />,
    "QuestionMarkIcon": <QuestionMarkIcon />,
    "QuoteIcon": <QuoteIcon />,
  },
  "R": {
    "RadiobuttonIcon": <RadiobuttonIcon />,
    "ReaderIcon": <ReaderIcon />,
    "ReloadIcon": <ReloadIcon />,
    "ResetIcon": <ResetIcon />,
    "ResumeIcon": <ResumeIcon />,
    "RocketIcon": <RocketIcon />,
    "RotateCounterClockwiseIcon": <RotateCounterClockwiseIcon />,
    "RowSpacingIcon": <RowSpacingIcon />,
    "RowsIcon": <RowsIcon />,
    "RulerHorizontalIcon": <RulerHorizontalIcon />,
    "RulerSquareIcon": <RulerSquareIcon />,
  },
  "S": {
    "ScissorsIcon": <ScissorsIcon />,
    "SectionIcon": <SectionIcon />,
    "SewingPinIcon": <SewingPinIcon />,
    "SewingPinFilledIcon": <SewingPinFilledIcon />,
    "ShadowIcon": <ShadowIcon />,
    "ShadowInnerIcon": <ShadowInnerIcon />,
    "ShadowNoneIcon": <ShadowNoneIcon />,
    "ShadowOuterIcon": <ShadowOuterIcon />,
    "Share1Icon": <Share1Icon />,
    "Share2Icon": <Share2Icon />,
    "ShuffleIcon": <ShuffleIcon />,
    "SizeIcon": <SizeIcon />,
    "SketchLogoIcon": <SketchLogoIcon />,
    "SlashIcon": <SlashIcon />,
    "SliderIcon": <SliderIcon />,
    "SpaceBetweenHorizontallyIcon": <SpaceBetweenHorizontallyIcon />,
    "SpaceBetweenVerticallyIcon": <SpaceBetweenVerticallyIcon />,
    "SpaceEvenlyHorizontallyIcon": <SpaceEvenlyHorizontallyIcon />,
    "SpaceEvenlyVerticallyIcon": <SpaceEvenlyVerticallyIcon />,
    "SpeakerLoudIcon": <SpeakerLoudIcon />,
    "SpeakerModerateIcon": <SpeakerModerateIcon />,
    "SpeakerOffIcon": <SpeakerOffIcon />,
    "SpeakerQuietIcon": <SpeakerQuietIcon />,
    "SquareIcon": <SquareIcon />,
    "StackIcon": <StackIcon />,
    "StarIcon": <StarIcon />,
    "StarFilledIcon": <StarFilledIcon />,
    "StitchesLogoIcon": <StitchesLogoIcon />,
    "StopIcon": <StopIcon />,
    "StopwatchIcon": <StopwatchIcon />,
    "StretchHorizontallyIcon": <StretchHorizontallyIcon />,
    "StretchVerticallyIcon": <StretchVerticallyIcon />,
    "StrikethroughIcon": <StrikethroughIcon />,
    "SunIcon": <SunIcon />,
    "SwitchIcon": <SwitchIcon />,
    "SymbolIcon": <SymbolIcon />,
  },
  "T": {
    "TableIcon": <TableIcon />,
    "TargetIcon": <TargetIcon />,
    "TextIcon": <TextIcon />,
    "TextAlignBottomIcon": <TextAlignBottomIcon />,
    "TextAlignCenterIcon": <TextAlignCenterIcon />,
    "TextAlignJustifyIcon": <TextAlignJustifyIcon />,
    "TextAlignLeftIcon": <TextAlignLeftIcon />,
    "TextAlignMiddleIcon": <TextAlignMiddleIcon />,
    "TextAlignRightIcon": <TextAlignRightIcon />,
    "TextAlignTopIcon": <TextAlignTopIcon />,
    "TextNoneIcon": <TextNoneIcon />,
    "ThickArrowDownIcon": <ThickArrowDownIcon />,
    "ThickArrowLeftIcon": <ThickArrowLeftIcon />,
    "ThickArrowRightIcon": <ThickArrowRightIcon />,
    "ThickArrowUpIcon": <ThickArrowUpIcon />,
    "TimerIcon": <TimerIcon />,
    "TokensIcon": <TokensIcon />,
    "TrackNextIcon": <TrackNextIcon />,
    "TrackPreviousIcon": <TrackPreviousIcon />,
    "TransparencyGridIcon": <TransparencyGridIcon />,
    "TrashIcon": <TrashIcon />,
    "TriangleDownIcon": <TriangleDownIcon />,
    "TriangleLeftIcon": <TriangleLeftIcon />,
    "TriangleRightIcon": <TriangleRightIcon />,
    "TriangleUpIcon": <TriangleUpIcon />,
    "TwitterLogoIcon": <TwitterLogoIcon />,
  },
  "U": {
    "UnderlineIcon": <UnderlineIcon />,
    "UpdateIcon": <UpdateIcon />,
    "UploadIcon": <UploadIcon />,
  },
  "V": {
    "ValueIcon": <ValueIcon />,
    "ValueNoneIcon": <ValueNoneIcon />,
    "VercelLogoIcon": <VercelLogoIcon />,
    "VideoIcon": <VideoIcon />,
    "ViewGridIcon": <ViewGridIcon />,
    "ViewHorizontalIcon": <ViewHorizontalIcon />,
    "ViewNoneIcon": <ViewNoneIcon />,
    "ViewVerticalIcon": <ViewVerticalIcon />,
  },
  "W": {
    "WidthIcon": <WidthIcon />,
  },
  "Z": {
    "ZoomInIcon": <ZoomInIcon />,
    "ZoomOutIcon": <ZoomOutIcon />,
  }
}